# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officedata',
            name='boughtdate',
            field=models.DateField(verbose_name='boughtdate'),
        ),
    ]
