# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20170206_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyAgents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warantyAgentName', models.CharField(max_length=200)),
                ('warantyAgentLocation', models.CharField(max_length=200)),
                ('WarantyAgentPhoneNumber', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='officedata',
            name='WarantyAgentPhoneNumber',
        ),
        migrations.RemoveField(
            model_name='officedata',
            name='warantyAgentLocation',
        ),
        migrations.RemoveField(
            model_name='officedata',
            name='warantyAgentName',
        ),
        migrations.AddField(
            model_name='warrantyagents',
            name='productName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.OfficeData'),
        ),
    ]
