# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_auto_20170206_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='officedata',
            name='product_type',
            field=models.CharField(choices=[('O', 'General Office'), ('M', 'LeasableMachinary'), ('L', 'LeasableAgricultural')], default='O', max_length=1),
        ),
    ]
