# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_officedata_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officedata',
            name='modelDate',
            field=models.DateField(blank=True, verbose_name='model date'),
        ),
        migrations.AlterField(
            model_name='officedata',
            name='modelNo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='officedata',
            name='previousEvaluationDate',
            field=models.DateField(blank=True, verbose_name='previously evaluated on'),
        ),
        migrations.AlterField(
            model_name='officedata',
            name='product_type',
            field=models.CharField(choices=[('O', 'General Office'), ('M', 'Machinary'), ('L', 'Agricultural')], default='O', max_length=1),
        ),
    ]
