# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_auto_20170212_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officedata',
            name='modelDate',
            field=models.DateField(blank=True, null=True, verbose_name='model date'),
        ),
        migrations.AlterField(
            model_name='officedata',
            name='modelNo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
