# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_auto_20170212_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officedata',
            name='previousEvaluationDate',
            field=models.DateField(blank=True, null=True, verbose_name='previously evaluated on'),
        ),
    ]
