# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 03:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('public', '0011_auto_20170214_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicuserdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PublicUser',
        ),
    ]
