# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0012_auto_20170214_0916'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicUserData',
        ),
    ]
