# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0014_publicuserdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicuserdata',
            name='modelNo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
